version: '3.8'

services:
  society-management:
    build: .
    ports:
      - "8081:8081"
    container_name: society-management
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-society-management:5432/dbsm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
    links:
      - 'db-society-management:database'
  db-society-management:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: dbsm
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-data:
    driver: local